**d) Create one more feature and add this column to the dataset (you can use mutate function in
R for this). For example, you can calculate the current age of the car by subtracting “Year” value
from the current year.**

In [2]:
import os
import pandas as pd

df=pd.read_csv('/content/missing_values_replaced.csv')
#obtaining current age of the car and storing it under the new column 'Age'
df['Age']=2024-df['Year']
#calculating efficiency and storing it under the new column 'Efficiency'
df['Efficiency']=df['Mileage']/df['Power']

df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age,Efficiency
0,0,0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50,9,0.155864
1,1,1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.00,1199.0,88.70,5.0,4.50,13,0.146561
2,2,2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00,12,0.234002
3,3,3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74,11,0.107955
4,4,4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461.0,63.10,5.0,3.50,11,0.365769

In [3]:
df.to_csv('/content/age_and_efficiency.csv')